isDebug: true
dadaBaseUrl: '127.0.0.1'
dataBaseDriveV8: 'com.mysql.cj.jdbc.Driver'
dataBaseDriveV5: 'com.mysql.jdbc.Driver'
dataBaseParam: 'useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true'

### log config ###
logging:
  level:
    root: info
    druid:
      sql: debug
spring:
  jpa:
    show-sql: false #是否在控制台显示数据库语句
    hibernate:
      ddl-auto: update #每次启动时如何操作对应表
    database-platform: org.hibernate.dialect.MySQL8Dialect #设置jpa方言为mysql
  redis:
    host: 127.0.0.1
    port: 36379
    database: 0
    jedis:
      pool:
        max-active: 10
  datasource:
    druid:
      driverClassName: ${dataBaseDriveV8} #数据库驱动
      url: jdbc:mysql://${dadaBaseUrl}:33306/red_package?useSSL=false&${dataBaseParam} #数据库地址
      username: root #数据库用户名
      password: root #数据库密码
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      filters: stat,wall,slf4j
      initial-size: 5
      max-active: 20
      max-pool-prepared-statement-per-connection-size: 20
      max-wait: 60000
      min-evictable-idle-time-millis: 30000
      min-idle: 5
      reset-stat-enable: false
      stat-view-servlet:
        login-password: admin
        login-username: admin
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      use-global-data-source-stat: true
      validation-query: select 'x'
      filter:
        slf4j:
          connection-log-enabled: false
          enabled: false
          result-set-log-enabled: true
          statement-executable-sql-log-enable: true
          statement-log-enabled: false
#prod
appid: wx8c7c9e690f27adee
secret: 520cb07d1f1ee5e019c363463dd5725a
tokenUrl: 'https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${appid}&secret=${secret}'

