isDebug: false
dadaBaseUrl: '192.168.3.20'
dataBaseDriveV8: 'com.mysql.cj.jdbc.Driver'
dataBaseDriveV5: 'com.mysql.jdbc.Driver'
dataBaseParam: 'useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true'

mail:
  host: 'smtp.qq.com'
  username: 'xxxxx@qq.com'
  password: 'xxxxx'
  source: 'xxxxx@qq.com'
  port: '465'
  isAuth: true
  isDebug: true
logging:
  pattern:
    level: info
spring :
  rabbitmq:
    host: 192.168.3.20
    port: 5672
    username: crabapples
    password: crabapples
    virtual-host: /crabapples
  redis:
    host: 192.168.3.20
    port: 6379
    password: crabapples
    database: 0
    jedis:
      pool:
        max-active: 10
  datasource:
    driverClassName: ${dataBaseDriveV8} #数据库驱动
    url: jdbc:mysql://${dadaBaseUrl}:3306/learn?useSSL=false&${dataBaseParam} #数据库地址
    username: learn #数据库用户名
    password: learn #数据库密码
