crabapples:
  AES_KEY: crabapples
  REDIS_PREFIX: crabapples
  TOKEN_CACHE_TIME: 30
  SALT: crabapples

server:
  port: 9093 #启动端口
#  servlet:
#    context-path: /learn #应用名
nacos:
  config:
    server-addr: '192.168.3.20:8848'
spring:
  application:
    name: learn
  profiles:
    active: dev #激活的配置文件
  #  thymeleaf:
  #    prefix: classpath:templates/ #thymeleaf模板引擎路径
  #    suffix: .html #thymeleaf模板后缀
  #    cache: false
  #    mode: HTML5
  cache:
    jedis:
      pool:
        max-active: 10
    redis:
      time-to-live: 60000
  servlet:
    multipart:
      max-file-size: 100MB
logging:
  file:
    name: d:/logs/springboot-shiro-jpa
