crabapples:
  AES_KEY: crabapples
  REDIS_PREFIX: crabapples
  TOKEN_CACHE_TIME: 30
  SALT: crabapples

server:
  port: 9093 #启动端口
#  servlet:
#    context-path: /learn #应用名
spring:
  application:
    name: learn
  profiles:
    active: prod #激活的配置文件
  cache:
    jedis:
      pool:
        max-active: 10
    redis:
      time-to-live: 60000
logging:
  file:
    name: /var/log/red-package

